DROP TABLE ALERT_RECORD;

CREATE TABLE ALERT_RECORD
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DATE TIMESTAMP NOT NULL,
    MESSAGE VARCHAR(4096) NOT NULL,
    CONSTRAINT primary_key PRIMARY KEY (ID),
    CONSTRAINT UNIQUE
);
